---
name: "RTSP 2 MJPEG"
description: "RTSP 2 MJPEG for creating MJPEG Stream and Still image urls from IP-Camera"
version: 1.0.0
slug: "rtsp2mjpeg"
init: false
webui: http://[HOST]:[PORT:8090]
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
hassio_role: homeassistant
image: docker.io/norskfjellgeit/ha-rtsp2mjpeg
panel_icon: mdi:camera
panel_title: FFServer UI
options:
  camera_url: "rtsp://10.0.0.6:554/s0"
  camera_width: 1920
  camera_height: 1080
  camera_fps: 2
  camera_still_fps: 1
schema:
  camera_url: str
  camera_width: int
  camera_height: int
  camera_fps: int
  camera_still_fps: int
ports:
  8090/tcp: 8090
ports_description:
  8090/tcp: HTTP